# Generated by Django 4.2.5 on 2024-02-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Species", models.CharField(max_length=100)),
                ("Breed", models.CharField(max_length=100)),
                ("Age", models.IntegerField()),
                (
                    "Gender",
                    models.CharField(
                        choices=[("male", "male"), ("female", "female")], max_length=50
                    ),
                ),
                ("Description", models.TextField()),
            ],
        ),
    ]
